FROM gitpod/workspace-full:latest

USER root
# Install custom tools, runtime, etc.
RUN sudo apt-get install libgtest-dev \
    && cd /usr/src/googletest/googletest \
    && sudo mkdir build \
    && cd build \
    && sudo cmake .. \
    && sudo make \
    && sudo cp libgtest* /usr/lib/  \
    && cd .. \
    && sudo rm -rf build

