# Example workflow
name: Formatter

on:
  push:
    branches:
      - master

jobs:
  
  jsformatting: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sane-fmt/action@master
